### ISSUE TITLE
How to map temperature range with color range 

### ISSUE THREAD

**Issue by giegiey** [pimoroni/mlx90640-library#43]
Now we are getting normal body temperature color as pink. How do i shift the color range to yellow . Im using sdlscale.cpp in examples folder.

**Comment by Gadgetoid** [comment]
All of the colour mapping is handled by `put_pixel_false_colour` which you can see here:

https://github.com/pimoroni/mlx90640-library/blob/bac70fab79896fdc8bcf41c3f55b8c01fab72e13/examples/src/sdlscale.cpp#L46-L76

It maps atemperature range of 5.0c to 50.0c to the set of 7 available colours from black (0, 0, 0) to white (1, 1, 1). These are just floating-point amounts of red, green and blue respectively so you can tune the number and colour of them to your heart's content.

Indeed normal body tempererature converts as colour 4.13 ( `(36-vmin)/(vmax-vmin) * (NUM_COLORS-1)` ) which is ~10% of the way between the 5th and 8th colours (red and purple respectively) which will, indeed, result in pink.

If you want a pure yellow for ~36 degrees then you'll want to change the colours so that it lands on `(1, 1, 0)` or change the min/max bounds so that  `(36-vmin)/(vmax-vmin) * (NUM_COLORS-1) == 3`

Rewrite this to to find vmax: `vmax = 36 * (7-1) / 3 - vmin` and solve to get `67.0`

So, a really lazy fix without changing the number of colours or `vmin` might be to change the line `float vmax = 50.0` to `float vmax = 67.0`.
